- id: version-sync
  name: Check Versions Consistency
  description: "Ensures that pyproject.toml and package.json versions match."
  entry: python -m version_sync
  language: python
  pass_filenames: false
